### ISSUE TITLE
GOCC “go get” fails on go version 1.16

### ISSUE THREAD

**Issue by matt2909** [uber-research/GOCC#3]
The “go get” command listed in the README fails with go version 1.16. Is their a specific version requirement to get GOCC working?

**Comment by lollllcat** [comment]
Thanks for the interest and sorry for the super late reply. There have been a lot of changes on the go module, go111module, etc. If you simply want to run the tool, then you can try to check out this commit 13590bf4be6331d065f7d951614e898689536bb2. Then do the following should work:

- go mod init github.com/uber-research/GOCC
- go mod tidy
- cd tools/gocc
- go build
